<div id="header">
<h1 class="title">CS2900 :- Topic 3 Lab</h1>
<h2 class="author">Hugh Shanahan and Tom Kuipers</h2>
</div>

The learning outcomes of this session are:

-   To have an introductory understanding of solving linear equations in
    NumPy and be introduced to ill-conditioned matrices. To have
    experience of using the NumPy reference document pages.

-   To become familiar with projecting onto sub-spaces.


Set up
======


Be sure to import NumPy just as you did in the previous lab sheets.

# Moodle testing

To get feedback on the checkpoints you do in this lab, please go to the following [moodle quiz](https://moodle.royalholloway.ac.uk/mod/quiz/view.php?id=965459). There will be a question for each checkpoint. You will get feedback on every checkpoint. You can retry the questions as many times as you wish. 

In [13]:
import numpy as np
import math

# Rectangular matrices

As noted in the lectures we can define rectangular matrices:

In [14]:
A = np.array([[1,2,3],[3,2,1]])
B = np.array([[1,1,1,2],[-1,-1,0,3],[0,1,0,1]])
print(A)
print(B)

[[1 2 3]
 [3 2 1]]
[[ 1  1  1  2]
 [-1 -1  0  3]
 [ 0  1  0  1]]
[[1 2 3]
 [3 2 1]]
[[ 1  1  1  2]
 [-1 -1  0  3]
 [ 0  1  0  1]]


## CHECKPOINT 1


-**Define the variable `AB` equal to the multiplication $AB$**

-**What would happen if you try to compute $BA$?** (*Look at the feedback from the moodle quiz on this point.*)

**Try and predict what will happen before you do this.** 



In [15]:
# Your code here...



Solving linear equations
========================

As discussed in Topic 3 we can solve equations of the form:
$$\mathbf{A} \underline{x} \;\; = \;\; \underline{b} \;\; ,
(1)$$ where we know $\mathbf{A}$ and $\underline{b}$
but not $\underline{x}$. 

In NumPy this can be computed using the function `numpy.linalg.solve`.

Solving
-------
Go to the NumPy reference pages
    <a href="https://docs.scipy.org/doc/numpy/reference/" class="uri">https://docs.scipy.org/doc/numpy/reference/</a>
    and find the page on `numpy.linalg.solve` and determine how to use it
    to solve the above equation.

In [ ]:
# You can use this code cell to play around with solving...



## CHECKPOINT 2

- **Create two lists `As` and `bs` which are composed of four NumPy matrices and four NumPy vectors respectively. They should have the following values (ensure that all the values are of type `float`).**

$$\begin{aligned}
\mathbf{As}[0] = 
\begin{pmatrix}
10 & 1 \\
1 & 10 
\end{pmatrix}
&& \underline{bs}[0] = 
\begin{pmatrix}
200 \\
-200
\end{pmatrix} \\
\mathbf{As}[1] = 
\begin{pmatrix}
10 & 1 & 2\\
1 & 10 & -3 \\
3 & 15 & -3 
\end{pmatrix}
&& \underline{bs}[1] = 
\begin{pmatrix}
200 \\
-200 \\
-150
\end{pmatrix} \\
\mathbf{As}[2] = 
\begin{pmatrix}
10 & 1 & 2\\
1 & 10 & -3 
\end{pmatrix}
&& \underline{bs}[2] = 
\begin{pmatrix}
200 \\
-200 \\
-150
\end{pmatrix} \\
\mathbf{As}[3] = 
\begin{pmatrix}
1 & 1 \\
2 & 2
\end{pmatrix}
&& \underline{bs}[3] = 
\begin{pmatrix}
200 \\
-200
\end{pmatrix} \end{aligned}$$
    
- **Use `numpy.linalg.solve` to solve equations of the form (1) (described above) to create a list `xs` where each entry is a solution to the corresponding value in `As` and `bs`. So for example xs[0] should the solution to As[0] xs[0] = bs[0]; xs[0] should the solution to As[1] xs[1] = bs[1] and so on.**

**NOTE:** Some of these instances will create an error. Ask yourself why did this happen? (Hint - have a look at the error message that gets returned). For those cases where you get an error, the corresponding entry of xs should have the value -1.

In [20]:
# Your code here...
  


[ 22.22222222 -22.22222222]
[ -1.31578947  10.52631579 101.31578947]
-1
-1
[ 22.22222222 -22.22222222]
[ -1.31578947  10.52631579 101.31578947]
-1
-1


## CHECKPOINT 3

- **Write a function `checkNull` that accepts a single argument `p` which is a NumPy vector.**
    - **`checkNull` returns a boolean that is `True` is the length of the vector is less than $10^{-6}$ and `False` otherwise.**


- **Create new lists `Cs`, `ds` and `ys` which are the matrices and vectors inside `As`, `bs` and `xs` where there is a solution (i.e. the code does not throw an error).**

In [34]:
# Your code here...





## CHECKPOINT 4

**One can check if the above approach is correct by checking if**

$$
\begin{equation}
\mathbf{C}[i] \underline{y}[i] - \underline{d}[i] \;\; = \;\; \underline{0} \;\;\; (2)
\end{equation}
$$

(where $i$ is the $i$th entry of each of the lists - so if all of the above cases of `A` and `b` have solutions, then $i=0 \dots 3$.)

- **Write another function `testSolutions` which accepts as arguments `C`, `d` and `y`.**
    - **`testSolutions` returns a tuple of _boolean_ values that are return values of `checkNull`, where the vector passed to it is the left hand side of (2) for each entry of $i$.**

In [39]:
# Your code here...




# Nearly singular matrices

We’ve note previously that many matrices are singular -
i.e. non-invertible. There are also many matrices which are nearly
singular. The upshot of this is that solutions to equation **(1)**
are very unstable. This can even turn up in simple $2 \times 2$
matrices.

## CHECKPOINT 5

**Consider the following very similar matrices:**

$$\mathbf{E1} = 
    \begin{pmatrix}
    400.0 & -201.0\\
    -800.0&401.0 
    \end{pmatrix}
    \;\; 
    \mathbf{E2} = 
    \begin{pmatrix}
    401.0 & -201.0\\
    -800.0&401.0 
    \end{pmatrix}$$

**For**

$$\underline{z} \;\; = \;\; 
    \begin{pmatrix}
    200.0 \\
    -200.0
    \end{pmatrix}$$ 
    
**Compute the solutions $x1$, $x2$ for** 
$$\begin{aligned}
    \mathbf{E1} \underline{x1} \;\; &=& \underline{z} \;\; ,\\
    \mathbf{E1} \underline{x2} \;\; &=& \underline{z} \;\; .\end{aligned}$$
    
**Compare these solutions. How similar are they? Why do you think that has happened?**

In [40]:
# Your code here...


[-100. -200.]
[40000.00000004 79800.00000007]
[-100. -200.]
[40000.00000004 79800.00000007]


# Projection

As discussed in Topic 3, we can project a vector in a particular space
onto a sub-space (e.g. project a vector in 2 dimensions onto a line,
project a vector in 3 dimensions onto a plane and so on).

To do this we need a orthonormal basis for the sub-space.

We then construct a matrix $\mathbf{P}$ whose rows are made up of the
unit vectors of the orthonormal basis. 

If the vector we want to project
is $\underline{x}$ then
$\mathbf{M} = \mathbf (\mathbf{P}^{\intercal} \mathbf{P}) \underline{x}$ is the projected
vector.

$\mathbf{M}$ is matrix we can use to project *any* vector in the space onto the sub-space.

# 2 Dimensions

We’ll first consider a 2 dimensional example with the following line.

<figure>
<img src="Lab3_1.png" alt="image" style="height:4cm" />
</figure>

We define

In [55]:
u_hat = np.array([1.0/math.sqrt(2),1.0/math.sqrt(2)])

In [56]:
P = np.array([u_hat])

    (It's important make sure you have the square bracket ordering correct.)

In [57]:
Pt = np.transpose(P)

In [58]:
M = np.matmul(Pt,P)

In [59]:
print(M)

[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]


## CHECKPOINT 6

**One can now use $\mathbf{M}$ to project a vector onto this line.**

- **Define the list `X_cp6` ($X$) where**

$$\begin{aligned}
X[0] = \begin{pmatrix}
1\\ 0 
\end{pmatrix} \\
X[1] = 
\begin{pmatrix}
1\\ 1 
\end{pmatrix} \\
X[2] = 
\begin{pmatrix}
0 \\ -1 
\end{pmatrix}\\
X[3] = 
\begin{pmatrix}
1\\ -1 
\end{pmatrix}
\end{aligned}
$$ 

- **Create a list `Y_cp6` where $Y[i] = M X[i]$.**
    
**What did you find? Did they match with what you expected?**

In [53]:
# Your code here...


    



We could have picked a different unit vector to represent the same line, namely;

$\underline{\hat{u}} = \begin{pmatrix}-1/\sqrt 2 \\ -1 / \sqrt 2\end{pmatrix}$.
    
## CHECKPOINT 7
    
- **Compute `Mnew` using the same procedure described at the start of this section with $\underline{\hat{u}}$.**

**Compare  this with `M`. Are they different?**

In [60]:
# Your code here...




[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]


# 3 Dimensions

This can be extended to three dimensions. In this case, we will consider
the projection from 3 dimensions to the x-y plane and we shall pick as
an orthonormal basis 

$$\underline{\hat{u}} =
\begin{pmatrix}
1 \\
0 \\
0 
\end{pmatrix} \;\; 
\underline{\hat{v}} =
\begin{pmatrix}
0 \\
1 \\
0 
\end{pmatrix}$$

## CHECKPOINT 8

- **Define the variable `P_3` which is equal to the corresponding matrix $\mathbf{P_3}$ using** $\underline{\hat{u}}$ and $\underline{\hat{v}}$ 

- **Hence, compute the variable `M_3` $ = \mathbf{P_3}^{\intercal}\mathbf{P_3}$.**

In [62]:
# Your code here...



[[1 0 0]
 [0 1 0]
 [0 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 0]]


## CHECKPOINT 9

- **Compute the list `X_3` where**

$$
\begin{aligned}
X3[0] = 
\begin{pmatrix}
1 \\ 1 \\ 1
\end{pmatrix}, \\ 
X3[1] = \begin{pmatrix}
1 \\ 0 \\ 0
\end{pmatrix}, \\ 
X3[2] = 
\begin{pmatrix}
0 \\ 0 \\ 1
\end{pmatrix} \\
\end{aligned}
$$ 

- **Compute the list `Y_3` where $Y3[i] = \mathbf{M_3} \underline{X3[i]}$.**

**Do the results match what you expected?**

In [63]:
# Your code here...



[array([1, 1, 0]), array([1, 0, 0]), array([0, 0, 0])]
[array([1, 1, 0]), array([1, 0, 0]), array([0, 0, 0])]


## CHECKPOINT 10

**We can repeat above for different basis vectors to represent the same sub-space, namely**

$$\underline{\hat{u}} =
    \begin{pmatrix}
    1/\sqrt 2 \\
    1 / \sqrt 2\\
    0 
    \end{pmatrix} \;\; 
    \underline{\hat{v}} =
    \begin{pmatrix}
    1 / \sqrt 2 \\
    -1 / \sqrt 2\\
    0 
    \end{pmatrix}$$
    
**Compute the projection matrix `M_3alt` which is the projection matrix using these basis vectors and compare it with `M_3`.**

In [64]:
# Your code here...



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
